//@GeneratedCode
namespace QTChinnok.Logic.Controllers.Base
{
    using TEntity = Entities.Base.Genre;
    using TOutModel = Models.Base.Genre;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    
    public sealed partial class GenresController : EntitiesController<TEntity, TOutModel>, Contracts.Base.IGenresAccess
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public GenresController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public GenresController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal override TOutModel ToModel(TEntity entity)
        {
            var handled = false;
            TOutModel? result = default;
            
            BeforeToOutModel(entity, ref result, ref handled);
            if (handled == false || result == default)
            {
                result = new TOutModel(entity);
            }
            AfterToOutModel(entity, result);
            return result;
        }
        partial void BeforeToOutModel(TEntity entity, ref TOutModel? result, ref bool handled);
        partial void AfterToOutModel(TEntity entity, TOutModel result);
    }
}
