//@GeneratedCode
namespace QTChinnok.WpfApp.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    
    public partial class Track
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static Track()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public Track()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'AlbumId' generated by the generator.
        /// </summary>
        public IdType? AlbumId { get; set; }
        /// <summary>
        /// Property 'GenreId' generated by the generator.
        /// </summary>
        public IdType? GenreId { get; set; }
        /// <summary>
        /// Property 'MediaTypeId' generated by the generator.
        /// </summary>
        public IdType MediaTypeId { get; set; }
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String Name { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Composer' generated by the generator.
        /// </summary>
        public System.String? Composer { get; set; }
        /// <summary>
        /// Property 'Milliseconds' generated by the generator.
        /// </summary>
        public System.Int32 Milliseconds { get; set; }
        /// <summary>
        /// Property 'UnitPrice' generated by the generator.
        /// </summary>
        public System.Decimal UnitPrice { get; set; }
        /// <summary>
        /// Property 'Album' generated by the generator.
        /// </summary>
        public QTChinnok.WpfApp.Models.App.Album? Album { get; set; }
        /// <summary>
        /// Property 'Genre' generated by the generator.
        /// </summary>
        public QTChinnok.WpfApp.Models.Base.Genre? Genre { get; set; }
        /// <summary>
        /// Property 'MediaType' generated by the generator.
        /// </summary>
        public QTChinnok.WpfApp.Models.Base.MediaType? MediaType { get; set; }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WpfApp.Models.App.Track Create()
        {
            BeforeCreate();
            var result = new QTChinnok.WpfApp.Models.App.Track();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WpfApp.Models.App.Track Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WpfApp.Models.App.Track();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.WpfApp.Models.App.Track instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.WpfApp.Models.App.Track instance, object other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Track other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, AlbumId, GenreId, MediaTypeId, Name, Composer, Milliseconds, UnitPrice, Album, Genre, MediaType);
        }
    }
}
