//@GeneratedCode
namespace QTChinnok.WebApi.Models.Base
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    
    public partial class Artist
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static Artist()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public Artist()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String? Name { get; set; }
        /// <summary>
        /// Property 'Albums' generated by the generator.
        /// </summary>
        public System.Collections.Generic.List<QTChinnok.WebApi.Models.App.Album> Albums { get; set; } = new();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.Base.Artist Create()
        {
            BeforeCreate();
            var result = new QTChinnok.WebApi.Models.Base.Artist();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.Base.Artist Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.Base.Artist();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.WebApi.Models.Base.Artist instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.Base.Artist instance, object other);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.Base.Artist Create(QTChinnok.Logic.Models.Base.Artist other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.Base.Artist();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTChinnok.Logic.Models.Base.Artist other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.Base.Artist instance, QTChinnok.Logic.Models.Base.Artist other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public void CopyProperties(QTChinnok.Logic.Models.Base.Artist other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Name = other.Name;
                Albums = other.Albums.Select(e => QTChinnok.WebApi.Models.App.Album.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.Logic.Models.Base.Artist other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.Logic.Models.Base.Artist other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public void CopyProperties(QTChinnok.WebApi.Models.Base.Artist other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Name = other.Name;
                Albums = other.Albums.Select(e => QTChinnok.WebApi.Models.App.Album.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.WebApi.Models.Base.Artist other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.WebApi.Models.Base.Artist other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.Artist other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Name, Albums);
        }
    }
}
