//@GeneratedCode
namespace QTChinnok.WebApi.Models.Base
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class MediaTypeEdit
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static MediaTypeEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public MediaTypeEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String? Name { get; set; }
    }
}
