//@GeneratedCode
namespace QTChinnok.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Genre;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial interface IGenresAccess : BaseContracts.IDataAccess<TOutModel>
    {
    }
}
