//@GeneratedCode
namespace QTChinnok.WebApi.Controllers.Base
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public sealed partial class GenresController : Controllers.GenericController<QTChinnok.Logic.Models.Base.Genre, QTChinnok.WebApi.Models.Base.GenreEdit, QTChinnok.WebApi.Models.Base.Genre>
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public GenresController(QTChinnok.Logic.Contracts.Base.IGenresAccess other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        new private QTChinnok.Logic.Contracts.Base.IGenresAccess? DataAccess => base.DataAccess as QTChinnok.Logic.Contracts.Base.IGenresAccess;
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        protected override QTChinnok.WebApi.Models.Base.Genre ToOutModel(QTChinnok.Logic.Models.Base.Genre accessModel)
        {
            var handled = false;
            var result = default(QTChinnok.WebApi.Models.Base.Genre);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTChinnok.WebApi.Models.Base.Genre.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTChinnok.Logic.Models.Base.Genre accessModel, ref QTChinnok.WebApi.Models.Base.Genre? outModel, ref bool handled);
        partial void AfterToOutModel(QTChinnok.WebApi.Models.Base.Genre outModel);
    }
}
