//@GeneratedCode
namespace QTChinnok.Logic.Contracts.App
{
    using TOutModel = Models.App.MusicCollection;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial interface IMusicCollectionsAccess : BaseContracts.IDataAccess<TOutModel>
    {
    }
}
