//@GeneratedCode
namespace QTChinnok.Logic.Contracts.App
{
    using TOutModel = Models.App.MusicCollection;
    ///
    /// Generated by the generator
    ///
    public partial interface IMusicCollectionsAccess : BaseContracts.IDataAccess<TOutModel>
    {
    }
}
