//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class AlbumEdit
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static AlbumEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public AlbumEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'ArtistId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'ArtistId' generated by the generator.
        /// </summary>
        public IdType ArtistId { get; set; }
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Artist' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Artist' generated by the generator.
        /// </summary>
        public QTChinnok.WebApi.Models.Base.Artist? Artist { get; set; }
    }
}
