//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    
    public partial class Album
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static Album()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public Album()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'ArtistId' generated by the generator.
        /// </summary>
        public IdType ArtistId { get; set; }
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Artist' generated by the generator.
        /// </summary>
        public QTChinnok.WebApi.Models.Base.Artist? Artist { get; set; }
        /// <summary>
        /// Property 'Tracks' generated by the generator.
        /// </summary>
        public System.Collections.Generic.List<QTChinnok.WebApi.Models.App.Track> Tracks { get; set; } = new();
        /// <summary>
        /// Property 'MusicCollections' generated by the generator.
        /// </summary>
        public System.Collections.Generic.List<QTChinnok.WebApi.Models.App.MusicCollection> MusicCollections { get; set; } = new();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.App.Album Create()
        {
            BeforeCreate();
            var result = new QTChinnok.WebApi.Models.App.Album();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.App.Album Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.App.Album();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.Album instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.Album instance, object other);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.WebApi.Models.App.Album Create(QTChinnok.Logic.Models.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.App.Album();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTChinnok.Logic.Models.App.Album other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.Album instance, QTChinnok.Logic.Models.App.Album other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public void CopyProperties(QTChinnok.Logic.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.WebApi.Models.Base.Artist.Create((object)other.Artist) : null;
                Tracks = other.Tracks.Select(e => QTChinnok.WebApi.Models.App.Track.Create((object)e)).ToList();
                MusicCollections = other.MusicCollections.Select(e => QTChinnok.WebApi.Models.App.MusicCollection.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.Logic.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.Logic.Models.App.Album other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public void CopyProperties(QTChinnok.WebApi.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.WebApi.Models.Base.Artist.Create((object)other.Artist) : null;
                Tracks = other.Tracks.Select(e => QTChinnok.WebApi.Models.App.Track.Create((object)e)).ToList();
                MusicCollections = other.MusicCollections.Select(e => QTChinnok.WebApi.Models.App.MusicCollection.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.WebApi.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.WebApi.Models.App.Album other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Album other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, ArtistId, Title, Artist, Tracks, MusicCollections);
        }
    }
}
