//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class MusicCollectionEdit
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static MusicCollectionEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public MusicCollectionEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String Name { get; set; } = string.Empty;
    }
}
