//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class TrackEdit
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static TrackEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public TrackEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Property 'AlbumId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'AlbumId' generated by the generator.
        /// </summary>
        public IdType? AlbumId { get; set; }
        /// <summary>
        /// Property 'GenreId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'GenreId' generated by the generator.
        /// </summary>
        public IdType? GenreId { get; set; }
        /// <summary>
        /// Property 'MediaTypeId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'MediaTypeId' generated by the generator.
        /// </summary>
        public IdType MediaTypeId { get; set; }
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String Name { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Composer' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Composer' generated by the generator.
        /// </summary>
        public System.String? Composer { get; set; }
        /// <summary>
        /// Property 'Milliseconds' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Milliseconds' generated by the generator.
        /// </summary>
        public System.Int32 Milliseconds { get; set; }
        /// <summary>
        /// Property 'UnitPrice' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'UnitPrice' generated by the generator.
        /// </summary>
        public System.Decimal UnitPrice { get; set; }
        /// <summary>
        /// Property 'Album' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Album' generated by the generator.
        /// </summary>
        public QTChinnok.WebApi.Models.App.Album? Album { get; set; }
        /// <summary>
        /// Property 'Genre' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Genre' generated by the generator.
        /// </summary>
        public QTChinnok.WebApi.Models.Base.Genre? Genre { get; set; }
        /// <summary>
        /// Property 'MediaType' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'MediaType' generated by the generator.
        /// </summary>
        public QTChinnok.WebApi.Models.Base.MediaType? MediaType { get; set; }
    }
}
