//@GeneratedCode
namespace QTChinnok.Logic.Models.App
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class Album
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static Album()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public Album()
        {
            Constructing();
            _source = new Entities.App.Album();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        internal Album(Entities.App.Album source)
        {
            Constructing();
            _source = source;
            Constructed();
        }
        
        new internal Entities.App.Album Source
        {
            get => (Entities.App.Album)(_source!);
            set => _source = value;
        }
        
        /// <summary>
        /// Property 'ArtistId' generated by the generator.
        /// </summary>
        public IdType ArtistId
        {
            get => Source.ArtistId;
            set => Source.ArtistId = value;
        }
        
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title
        {
            get => Source.Title;
            set => Source.Title = value;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal void CopyProperties(Entities.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.Logic.Models.Base.Artist.Create((object)other.Artist) : null;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Album other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Album other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public void CopyProperties(QTChinnok.Logic.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.Logic.Models.Base.Artist.Create((object)other.Artist) : null;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.Logic.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.Logic.Models.App.Album other);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Album other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, ArtistId, Title, Artist, Tracks, MusicCollections);
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.Logic.Models.App.Album Create()
        {
            BeforeCreate();
            var result = new QTChinnok.Logic.Models.App.Album();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.Logic.Models.App.Album Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.Logic.Models.App.Album Create(QTChinnok.Logic.Models.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static QTChinnok.Logic.Models.App.Album Create(Entities.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, object other);
        static partial void BeforeCreate(QTChinnok.Logic.Models.App.Album other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, QTChinnok.Logic.Models.App.Album other);
        static partial void BeforeCreate(Entities.App.Album other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, Entities.App.Album other);
    }
}
